
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("951x633")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 633,
    width = 951,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    610.0,
    166.0,
    anchor="nw",
    text="Login",
    fill="#5996CB",
    font=("Montserrat Bold", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    677.5,
    274.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F4F8F5",
    highlightthickness=0
)
entry_1.place(
    x=481.0,
    y=245.0+29,
    width=393.0,
    height=27.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    677.5,
    357.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F4F8F5",
    highlightthickness=0
)
entry_2.place(
    x=481.0,
    y=328.0+29,
    width=393.0,
    height=27.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=565.0,
    y=411.0,
    width=225.0,
    height=55.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    196.0,
    318.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
